// Base de datos
const Data = {
  status: "success",
  items: [
    {
      id: 1,
      titulo: "Pizza americana",
      ingredientes: [
        "Salsa de tomate, ",
        "Queso, ",
        "Pepperoni y Aceitunas negras",
      ],
      precio: 13990,
      imagen: "americana", // Nombre de la imagen sin extension
      cantidad: 1,
    },
    {
      id: 2,
      titulo: "Pizza BBQ Chicken",
      ingredientes: [
        "Queso mozzarella, ",
        "Pollo, ",
        "Tocino, ",
        "Ceblolla, ",
        "Salsa BBQ",
      ],
      precio: 12990,
      imagen: "BBQChiken",
      cantidad: 1,
    },
    {
      id: 3,
      titulo: "Pizza Campesina",
      ingredientes: ["Pollo, ", "Pimiento, ", "Champiñón"],
      precio: 15990,
      imagen: "campesina",
      cantidad: 1,
    },
    {
      id: 4,
      titulo: "Pizza hawaiana",
      ingredientes: ["Queso mozzarella, ", "Piña, ", "Jamón"],
      precio: 15990,
      imagen: "hawaiana",
      cantidad: 1,
    },
    {
      id: 5,
      titulo: "Mechada BBQ",
      ingredientes: [
        "Doble porción de carne mechada, ",
        "queso mozzarella, ",
        "Queso parmesano y romano",
      ],
      precio: 14990,
      imagen: "mechadaBBQ",
      cantidad: 1,
    },
    {
      id: 6,
      titulo: "Pizza Vegan Queen",
      ingredientes: [
        "Champiñon, ",
        "pimiento verde, ",
        "aceitunas negras, ",
        "Not Meat (carneplant based) y queso vegano.",
      ],
      precio: 18990,
      imagen: "veganQueen",
      cantidad: 1,
    },
    {
      id: 7,
      titulo: "Pizza personalizada",
      ingredientes: [],
      precio: 16990,
      imagen: "arma-tu-pizza",
      cantidad: 1,
      link: "/personalizada",
    },
    {
      id: 9,
      titulo: "Coca cola",
      precio: 1000,
      cantidad: 1,
      imagen: "cocacola",
    },
    {
      id: 10,
      titulo: "Fanta",
      precio: 1000,
      cantidad: 1,
      imagen: "fanta",
    },
    {
      id: 11,
      titulo: "Watts Durazno",
      precio: 2000,
      cantidad: 1,
      imagen: "wattsdurazno",
    },
    {
      id: 12,
      titulo: "Watts Piña",
      precio: 2000,
      cantidad: 1,
      imagen: "wattspiña",
    },
    {
      id: 13,
      titulo: "Cachantun con Gas",
      precio: 1000,
      cantidad: 1,
      imagen: "congas",
    },
    {
      id: 14,
      titulo: "Cachantun sin Gas",
      precio: 1000,
      cantidad: 1,
      imagen: "singas",
    },
    {
      id: 15,
      titulo: "Salsa BBQ",
      precio: 990,
      cantidad: 1,
      imagen: "salsabbq",
    },
    {
      id: 16,
      titulo: "Salsa Garlic",
      precio: 990,
      cantidad: 1,
      imagen: "garlic",
    },
    {
      id: 17,
      titulo: "Salsa Picante",
      precio: 990,
      cantidad: 1,
      imagen: "salsapicante",
    },
    {
      id: 18,
      titulo: "Salsa tomate",
      precio: 990,
      cantidad: 1,
      imagen: "salsatomate",
    },
  ],
  locales: [
    {
      id: 1,
      nombre: "Local Maipú",
      ubicacion: ["Santiago", "Maipú", "Del rey", "2038"],
      imagen: "maipu",
      descripcion:
        "Esta ubicada cerca del metro santiago bueras" +
        ", cuenta con delivery propio y externo",
    },
    {
      id: 2,
      nombre: "Local Providencia",
      ubicacion: ["Santiago", "Providencia", "Génova", "8302"],
      imagen: "providencia",
    },
    {
      id: 3,
      nombre: "Local San Miguel",
      ubicacion: ["Santiago", "San Miguel", "Maurice Ravel", "7777"],
      imagen: "sanmiguel",
    },
  ],
};

export default Data;
